default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: alpha_blog_development
  username: archman
  password: archman
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432   
test:
  adapter: postgresql
  database: alpha_blog_test
  username: archman
  password: archman
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432   
production:
  <<: *default
  database: alpha_blog_production
